Adding sending of client txs

diff --git a/MakeFile b/MakeFile
--- a/MakeFile
+++ b/MakeFile
@@ -9,6 +9,7 @@ APTOS_CORE ?= $(abspath $(DSTEST_ROOT)/../aptos-core)
 DSTEST_BIN  := $(DSTEST_ROOT)/cmd/dstest/main
 APTOS_NODE  := $(APTOS_CORE)/target/release/aptos-node
 APTOS_CLI   := $(APTOS_CORE)/target/cli/aptos
+APTOS_CLIENT_BIN := $(DSTEST_ROOT)/cmd/aptos_client/main
 
 # venv
 VENV_DIR := $(DSTEST_ROOT)/.venv
@@ -36,6 +37,16 @@ FRAMEWORK_MRB := $(GENESIS_DIR)/framework.mrb
 # node config ports
 BASE_PORT ?= 8000
 
+# DSTest interceptor ports
+BASE_INTERCEPTOR_PORT ?= 10000
+
+# validator and fullnode network ports used in genesis for discovery
+VAL_NET_BASE ?= 6100
+FN_NET_BASE  ?= 6200
+
+# number of client accounts to generate and pre-fund (reusable)
+NUM_CLIENT_ACCOUNTS ?= 4
+
 # logs output directory
 RUN_ID ?= $(shell date +"%Y%m%d_%H%M%S")
 OUTPUT_BASE ?= output/aptos
@@ -58,6 +69,14 @@ LOG_LEVEL ?=
 # for checking liveness property, we set a timeout bound (in seconds)
 LIVENESS_TIMEOUT ?= 30
 
+# aptos.yml template vars
+SEED                 ?= 42
+PARAM_C              ?= 5
+PARAM_D              ?= 0
+PARAM_R              ?= 8
+CLIENT_REQUESTS      ?= 10
+CLIENT_PROB          ?= 0.01
+
 # -----------------------------
 # Helpers
 # -----------------------------
@@ -65,11 +84,12 @@ LIVENESS_TIMEOUT ?= 30
 help:
 	@echo "Targets:"
 	@echo "  make setup                 # create venv + install python deps"
-	@echo "  make build                 # build aptos-node + aptos-cli + dstest"
+	@echo "  make build                 # build aptos-node + aptos-cli + dstest + aptos-client"
 	@echo "  make framework    			# build framework.mrb (cached)"
 	@echo "  make genesis               # generate genesis.blob + waypoint.txt"
 	@echo "  make node-configs          # generate node.yaml + per-node dirs"
 	@echo "  make seeds                 # patch seed_addrs"
+	@echo "  make client-accounts       # generate workload accounts"
 	@echo "  make config                # generate config file aptos.yml for dsTest"
 	@echo "  make clean                 # kill nodes + wipe state"
 	@echo "  make run                   # run dsTest with CONFIG"
@@ -109,11 +129,16 @@ build-aptos:
 build-dstest:
 	cd $(DSTEST_ROOT)/cmd/dstest && go build -o main .
 
+.PHONY: build-aptos-client
+build-aptos-client:
+	cd $(DSTEST_ROOT)/cmd/aptos_client && go build -o main .
+
 .PHONY: build
-build: build-aptos build-dstest
-	@test -x $(APTOS_NODE) || (echo "Missing $(APTOS_NODE) (build-aptos failed?)"; exit 1)
-	@test -x $(APTOS_CLI)  || (echo "Missing $(APTOS_CLI)  (build-aptos failed?)"; exit 1)
-	@test -x $(DSTEST_BIN) || (echo "Missing $(DSTEST_BIN) (build-dstest failed?)"; exit 1)
+build: build-aptos build-dstest build-aptos-client
+	@test -x $(APTOS_NODE)        || (echo "Missing $(APTOS_NODE) (build-aptos failed?)"; exit 1)
+	@test -x $(APTOS_CLI)         || (echo "Missing $(APTOS_CLI)  (build-aptos failed?)"; exit 1)
+	@test -x $(DSTEST_BIN)        || (echo "Missing $(DSTEST_BIN) (build-dstest failed?)"; exit 1)
+	@test -x $(APTOS_CLIENT_BIN)  || (echo "Missing $(APTOS_CLIENT_BIN) (build-aptos-client failed?)"; exit 1)
 
 # -----------------------------
 # Aptos Framework MRB
@@ -148,10 +173,12 @@ genesis: framework setup build
 	APTOS_CORE="$(APTOS_CORE)" \
 	APTOS_CLI="$(APTOS_CLI)" \
 	PYTHON_BIN="$(VENV_PY)" \
+	VAL_NET_BASE="$(VAL_NET_BASE)" \
+	FN_NET_BASE="$(FN_NET_BASE)" \
 	bash $(APTOS_DIR)/aptos_prepare_localnet.sh
 
 .PHONY: node-configs
-node-configs: genesis
+node-configs: genesis client-accounts
 	BASE_DIR=$(BASE_DIR) \
 	GENESIS_DIR="$(GENESIS_DIR)" \
 	APTOS_CORE="$(APTOS_CORE)" \
@@ -166,6 +193,18 @@ seeds: node-configs
 	BASE_DIR="$(BASE_DIR)" CONFIG="$(CONFIG)" \
 	"$(VENV_PY)" "$(APTOS_DIR)/aptos_update_seeds.py"
 
+# -----------------------------------------------------------------
+# Client accounts generation for submitting txs to the blockchain
+# -----------------------------------------------------------------
+.PHONY: client-accounts
+client-accounts: genesis
+	BASE_DIR="$(BASE_DIR)" \
+	GENESIS_DIR="$(GENESIS_DIR)" \
+	APTOS_CORE="$(APTOS_CORE)" \
+	APTOS_CLI="$(APTOS_CLI)" \
+	NUM_CLIENT_ACCOUNTS="$(NUM_CLIENT_ACCOUNTS)" \
+	bash $(APTOS_DIR)/aptos_setup_client_accounts.sh
+
 # -----------------------------
 # dsTest config generation
 # -----------------------------
@@ -178,19 +217,20 @@ config:
 	echo "TestConfig:"; \
 	echo "  Name: $(TEST_NAME)"; \
 	echo "  Experiments: 1"; \
-	echo "  Iterations: 10"; \
+	echo "  Iterations: 20"; \
 	echo "  WaitDuration: 50"; \
 	echo "  StartupDuration: 10"; \
 	echo ""; \
 	echo "SchedulerConfig:"; \
 	echo "  Type: \"$(SCHED_TYPE)\""; \
 	echo "  Steps: 500"; \
-	echo "  Seed: 42"; \
-	echo "  Params: {\"c\": 5, \"d\": 0, \"r\": 8}"; \
+	echo "  Seed: $(SEED)"; \
+	echo "  ClientRequests: $(CLIENT_REQUESTS)"; \
+	echo "  Params: {\"c\": $(PARAM_C), \"d\": $(PARAM_D), \"r\": $(PARAM_R), \"client_request_probability\": $(CLIENT_PROB)}"; \
 	echo ""; \
 	echo "NetworkConfig:"; \
 	echo "  BaseReplicaPort: $(BASE_PORT)"; \
-	echo "  BaseInterceptorPort: 10000"; \
+	echo "  BaseInterceptorPort: $(BASE_INTERCEPTOR_PORT)"; \
 	echo "  Protocol: \"aptostcp\""; \
 	echo "  MessageType: Aptos"; \
 	echo ""; \
@@ -202,7 +242,12 @@ config:
 	echo "  Timeout: 100"; \
 	echo "  OutputDir:  $(OUTPUT_DIR)"; \
 	echo "  ReplicaScript: aptos/aptos_server.sh"; \
-	echo "  ClientScripts: []"; \
+	echo "  # NOTE: each ClientScripts entry must have a different clientId"; \
+	echo "  ClientScripts:"; \
+	echo "    - aptos/aptos_client.sh 0 0 5"; \
+	echo "    - aptos/aptos_client.sh 1 3 2"; \
+	echo "    - aptos/aptos_client.sh 2 1 5"; \
+	echo "    - aptos/aptos_client.sh 3 2 3"; \
 	echo "  CleanScript: aptos/aptos_clean.sh"; \
 	echo "  ReplicaParams:"; \
 	for i in $$(seq 0 $$(( $(NUM_REPLICAS) - 1 ))); do \
@@ -226,7 +271,7 @@ clean-outputs:
 
 .PHONY: run
 run:
-	@chmod +x $(APTOS_DIR)/aptos_server.sh $(APTOS_DIR)/aptos_clean.sh || true
+	@chmod +x $(APTOS_DIR)/aptos_server.sh $(APTOS_DIR)/aptos_clean.sh $(APTOS_DIR)/aptos_client.sh || true
 	@echo "Running dsTest with:"
 	@echo "  CONFIG=$(CONFIG)"
 	@echo "  BASE_DIR=$(BASE_DIR)"
